classes/PressShack/LibWP.php, classes/PublishPress/Permissions/PostFilters.php
This supports Status Control usage in Pro.
=> getPostStatuses(): add context parameter

modules/presspermit-collaboration/classes/Permissions/Collab/CapabilityFiltersAdmin.php
Note: changes for this feature were committed directly to the development branch.
=> Eliminate old workaround which clashed with list_posts solution

classes/PublishPress/Permissions.php
=> Disable the display_hints option by default

classes/PublishPress/Permissions.php
Reverts publishpress/PublishPress-Permissions#120
=> Revert "Disable the display_hints option by default"

modules/presspermit-collaboration/classes/Permissions/Collab/RESTInit.php
=> Gutenberg: could not view or edit page parent

common/css/presspermit.css
=> Gutenberg Post Status dropdown: bad alignment

classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsUI.php, readme.txt
=> Permissions metabox listed offered assignments for deleted WP roles

classes/PublishPress/Permissions/PluginUpdated.php
=> Remove invalid Authors post type filtering set by previous Permisisons version

classes/PublishPress/Permissions/DB/Permissions.php
=> Setting "Post-specific permissions take priority" ineffective

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/PostFilters.php, classes/PublishPress/Permissions/UI/SettingsTabCore.php
=> Search Results: option to exclude Media items

classes/PressShack/LibWP.php
=> Gutenberg Ramp - editor issues for Gutenberg-enabled post types

classes/PublishPress/Permissions/FrontFilters.php
=> Javascript error for "jQuery not defined" on some sites

classes/PublishPress/Permissions/UI/AgentPermissionsUI.php
=> Edit Permissions: "Mirror to" bulk action didn't work with Revise operation

press-permit-core.php
Merge beta release back to development
=> Release 3.3.7-beta2

classes/PublishPress/Permissions/TermFilters.php
=> REST term queries returned all terms, ignoring per_page parameter

classes/PublishPress/Permissions.php, modules/presspermit-import/classes/Permissions/ImportHooksAdmin.php
=> Undefined index db_version on first activation

modules/presspermit-collaboration/classes/Permissions/Collab/CommentFiltersAdmin.php
=> ODBC installations: Database error on comment count queries

classes/PublishPress/Permissions/UI/Dashboard/TermEdit.php
=> Edit Category screen: PHP Notice for deprecated action

classes/PublishPress/Permissions/DB/Permissions.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/PostFilters.php
* "Prevent Revisors from editing others' revisions" setting was not applied (also requires Revisions 2.4.2)
* Category-Specific Revise Permissions allowed an Author to fully edit posts in specified categories
* Category-Specific Revise Permissions allowed an Author to restore past revisions
* Specific Permissions to enable the Revise operation were ineffective for Contributors and Authors in some cases
Fixes #234
=> Revisions integration: various issues

modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/Admin.php
=> Revise permissions ineffective for Contributor, Author

modules/presspermit-collaboration/classes/Permissions/Collab/CommentFiltersAdmin.php
=> Comment Count filtered incorrectly for non-Administrators

classes/PublishPress/Permissions/DB/PermissionsMeta.php
=> ODBC installations: Comment query caused database error

classes/PublishPress/Permissions/PostFilters.php, classes/PublishPress/PermissionsHooks.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/DashboardFilters.php
=> Menus screen: Private posts not included in "Add menu items" search results

classes/PublishPress/Permissions/UI/Dashboard/TermsListing.php, classes/PublishPress/PermissionsHooks.php
=> Terms screen: Incorrect filtering with some configurations

modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
=> Divi Page Builder / theme: Specific Permissions do not enable editing

modules/presspermit-collaboration/classes/Permissions/Collab/Capabilities.php
=> Visual Composer: PHP error for undefined class Permissions\Capabilities

classes/PublishPress/Permissions/UI/Dashboard/Profile.php, classes/PublishPress/Permissions/UI/Dashboard/UsersListing.php
=> Multisite: Administrators who are not network admin cannot edit User Permissions

classes/PublishPress/Permissions/TermFilters.php, modules/presspermit-collaboration/classes/Permissions/Collab/REST_Workarounds.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
=> Term assignment permissions not applied correctly in Gutenberg

classes/PublishPress/Permissions/UI/Dashboard/TermEdit.php
Fixes #289
@todo: This may include some unnecessary precautions; review and possibly revert later
=> WPML: Edit Term screen had duplicate Permissions metaboxes

modules/presspermit-collaboration/classes/Permissions/Collab/Users.php
The reason for some sites not loading the Administrator's role level is unexplained, but this fix handles that condition, restoring proper User editing permissions when Permissions > Editing > User Management is set to "equal or lower role levels" or "lower role levels"
Fixes #294
=> Administrators can't assign roles or edit users with nonzero level

activation.php
=> Error activating Permissions Pro if Permissions is already active

modules/presspermit-collaboration/classes/Permissions/Collab/CommentFiltersAdmin.php
=> Slow comment count query for Contributors in wp-admin

classes/PublishPress/PermissionsHooksAdmin.php
This is a first pass at forcing object cache clearance on any Permissions setting or configuration update.
=> WP Engine object cache: intermittant page load failure

classes/PublishPress/Permissions/UI/Dashboard/TermEdit.php
=> Edit Category: Metaboxes for Editing and Assignment permissions blank

classes/PublishPress/Permissions/PostFilters.php
=> Non-Administrators with editing access to unpublished post can't view it with standard link

classes/PublishPress/Permissions/REST.php
New filters 'presspermit_rest_post_endpoints' and 'presspermit_rest_term_endpoints' support some custom REST API routes and endpoints for post, term queries
// Sample usage:
/*
add_filter('presspermit_rest_post_endpoints',
function($names) {
return array_merge($names, ['/api/v1/jobs' => ['jobs-post-type' => 'endpoint_class_or_function']]);
}
);
*/
This commit also cleans up some whitespace.
=> API : New filter for custom REST API routes and endpoints

classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/DashboardFilters.php, modules/presspermit-collaboration/classes/Permissions/CollabHooksAdmin.php
=> Remove Role Usage menu item; access by Settings > Advanced link instead

classes/PublishPress/Permissions/DB/Groups.php
=> Anonymous, All user meta groups: label as "Logged In" / "Not Logged In"

classes/PublishPress/Permissions/UI/AgentsAjax.php
=> User search boxes don't search user display name

classes/PublishPress/Permissions.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php, modules/presspermit-collaboration/classes/Permissions/CollabHooksAdmin.php
=> Revisions: Specific Permissions don't allow Contributor to revise others' pages

modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/DashboardWidgetsFilters.php
=> Glance That plugin: Widget content was cleared

classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsRenderUI.php
=> Remove brackets from WordPress role labels

classes/PublishPress/Permissions/DB/Groups.php, classes/PublishPress/Permissions/UI/Groups.php, classes/PublishPress/Permissions/UI/GroupsListTable.php, classes/PublishPress/Permissions/UI/GroupsQuery.php, classes/PublishPress/Permissions/UI/PluginPage.php
=> Introduce a Group Type column to the Groups table; List all types by default

classes/PublishPress/PermissionsHooksAdmin.php
This is not really an integration issue, but an Authors patch.
Non-Editors could be locked out of editing their own post due to "default author for new post" setting or manual Authors change.
Fixes #345
=> PublishPress Authors: non-Editors could be locked out of their own post

includes/promo/sync-promo.php
=> Sync promo screen: text change

classes/PublishPress/Permissions/UI/AgentPermissions.php, classes/PublishPress/Permissions/UI/Groups.php, common/css/presspermit.css
Also put an Add New button on the Edit Permission Group screen.
Fixes #323
=> Replace "Add new" link with button

modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
=> Divi Builder: Specific Permissions don't allow a non-Editor to edit Divi pages

classes/PublishPress/Permissions/UI/Handlers/Settings.php
=> Pro: File Access - uploads/.htaccess file not cleared on module deactivation

modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/Admin.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/AdminLegacy.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
Pending Revision Moinitors group membership don't control notifications for pending revisions submitted with a front end editor.
Fixes #394
=> Revisions Pro + Elementor, Divi or Beaver Builder : Pending Revision Monitors

classes/PublishPress/Permissions/DB/Permissions.php
If draft revisions enabled, apply term-specific Revise permissions to unpublished posts if constant PRESSPERMIT_REVISE_TERMS_FOR_UNPUBLISHED defined
=> Feature: Term-specific Revise permissions cover unpublished posts

classes/PublishPress/Permissions/PostFiltersFront.php
=> WPML: Archives widget doesn't output links if multiple languages configured

classes/PublishPress/Permissions/PostFilters.php, classes/PublishPress/PermissionsHooks.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/DashboardFilters.php
=> Menu Editor: Page / Post selection metaboxes - some private items not listed

classes/PublishPress/Permissions/PostFilters.php, classes/PublishPress/PermissionsHooks.php, modules/presspermit-collaboration/classes/Permissions/Collab/AdminFilters.php
=> WooCommerce: Failure / delay updating variations of variable product

activation.php
=> PHP Notice on plugin activation under some conditions

classes/PublishPress/Permissions/UI/Dashboard/TermEdit.php
=> PHP Notice on Edit Category screen

press-permit-core.php
=> Fatal error if very old version of Revisionary or PressPermit Core active

modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/ContentRoles.php
=> User Switching: First switched user inherits capabilities of current logged user on some sites

modules/presspermit-collaboration/classes/Permissions/Collab/NavMenus.php
=> Nav Menu Edit: Permissions config doesn't make private pages selectable

modules/presspermit-collaboration/classes/Permissions/Collab/AdminFilters.php, modules/presspermit-collaboration/classes/Permissions/Collab/NavMenus.php
=> Nav Menu Editor: Paging issues

classes/PublishPress/Permissions/UI/Handlers/Admin.php, classes/PublishPress/Permissions/UI/Handlers/Groups.php, classes/PublishPress/PermissionsHooksAdmin.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/Handlers/RoleUsage.php
=> WP Engine: Excessive queries in wp-admin

modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/CapabilityFilters.php
=> Assignment of custom status not properly controlled for private post types

modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/NavMenuQuery.php
=> Menu Editor: Posts metaboxes filtering, paging incorrect

classes/PublishPress/Permissions/PostFiltersFrontNonAdministrator.php
=> "Disable all filtering for anonymous users" doesn't stop Nav Menu filtering

classes/PublishPress/Permissions/DB/Permissions.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisions/Admin.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisions/CapabilityFilters.php
=> Hotfix 485 revisions3 specific permissions

classes/PublishPress/Permissions/Capabilities.php
=> PublishPress Revisions: Published custom post types not listed to Revisors under some configurations

classes/PublishPress/Permissions.php
=> Public Post Preview: Disable Permissions filtering for public preview requests

classes/PublishPress/Permissions/UI/AgentPermissionsUI.php
=> Edit Permissions: Missing post type label for stored permissions, PHP Notice

classes/PublishPress/PermissionsHooks.php
=> Classic Editor: Page permalink preview did not include parent pages

classes/PressShack/LibWP.php
WP 5.9 introduced a 'use_block_editor_for_post_type' filter which a function defined later than our filter application.  To avoid this conflict, remove the WP hook before our filter application.
=> WP 5.9: Avoid conflict on Block Editor check

modules/presspermit-collaboration/classes/Permissions/Collab/CapabilityFiltersAdmin.php
=> Error redirecting following post save with custom permissions in some cases

classes/PublishPress/Permissions/UI/Dashboard/ItemAjax.php
=> Specific Permissions could not be added using post editor metaboxes

modules/presspermit-collaboration/classes/Permissions/Collab/AdminWorkarounds.php, modules/presspermit-collaboration/classes/Permissions/Collab/Capabilities.php, modules/presspermit-collaboration/classes/Permissions/Collab/NavMenus.php, modules/presspermit-collaboration/classes/Permissions/CollabHooksAdmin.php
=> Non-administrators can't edit Menus on some installations

modules/presspermit-collaboration/classes/Permissions/CollabHooksCompat.php
=> PHP Warnings on admin dashboard

classes/PublishPress/Permissions/DB/GroupUpdate.php
=> Permission Group name / description update fails

classes/PublishPress/Permissions/DB/Permissions.php, classes/PublishPress/Permissions/ItemSave.php, classes/PublishPress/Permissions/UI/Handlers/AgentEdit.php
=> Category Permissions set for all post types are not stored properly

classes/PublishPress/Permissions/REST.php, modules/presspermit-collaboration/classes/Permissions/Collab/PostSaveHierarchical.php
=> User cannot publish page after autosave if restrictive editing permissions assigned

modules/presspermit-collaboration/classes/Permissions/Collab/PostTermsSave.php, modules/presspermit-collaboration/classes/Permissions/Collab/RESTInit.php, modules/presspermit-collaboration/classes/Permissions/Collab/REST_Workarounds.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
=> User cannot publish page after autosave

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/PostFilters.php, classes/PublishPress/Permissions/PostFiltersExtra.php, modules/presspermit-collaboration/classes/Permissions/Collab.php, modules/presspermit-collaboration/classes/Permissions/Collab/NavMenus.php, modules/presspermit-collaboration/classes/Permissions/Collab/PostEdit.php
=> Non-administrators can access Appearance menu, theme settings in WordPress 5.9

classes/PublishPress/Permissions/PostFiltersFrontNonAdministrator.php
=> Pro API: Filter to disable Nav Menu filtering for some post types

classes/PublishPress/Permissions/UI/AgentPermissions.php, classes/PublishPress/Permissions/UI/Dashboard/DashboardFilters.php, classes/PublishPress/Permissions/UI/Dashboard/Profile.php, classes/PublishPress/Permissions/UI/Dashboard/UserAjax.php
=> WP 6.0: Edit User screen - Custom group assignments not displayed

classes/PublishPress/Permissions/REST.php, classes/PublishPress/Permissions/TermFilters.php
=> Category / Term assignment restrictions not applied in Gutenberg editor

classes/PublishPress/Permissions/PageFilters.php
=> get_pages() filtering: depth argument not handled correctly in some cases

classes/PublishPress/Permissions/TermFilters.php
=> Category / Term permissions: exclusions not applied to get_the_terms filter

classes/PublishPress/Permissions/PostFilters.php
=> The Events Calendar: post queries filtered incorrectly with event venue

classes/PublishPress/Permissions/CapabilityFilters.php
=> Authors, Editors can't add a new post

classes/PublishPress/Permissions/TermFilters.php
=> REST post creation: Category Assign restrictions not applied without Edit restrictions

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/UI/SettingsAdmin.php, classes/PublishPress/PermissionsHooks.php
=> Multisite: Can't disable Display Branding option if plugin not network activated

classes/PublishPress/Permissions/ItemSave.php, classes/PublishPress/Permissions/PostSave.php, classes/PublishPress/Permissions/TermSave.php
=> Subpage Editing Permissions cleared when non-Administrator updates top level page

classes/PublishPress/Permissions/Triggers.php
constant: PRESSPERMIT_AUTOSET_AUTHOR
=> Set post_author to editing user if constant is defined

classes/PublishPress/Permissions/TermFilters.php
=> Term Permissions set for "Everyone" group restrict Administrators

classes/PublishPress/Permissions/PluginUpdated.php
=> Fatal error on plugin activation / deactivation under rare conditions

classes/PublishPress/Permissions/PostFiltersFront.php
=> Query Loop block: Sticky posts displayed redundantly

composer.json, press-permit-core.php, readme.txt
=> Implement instance protection library

classes/PublishPress/PermissionsHooks.php, composer.json
=> Implement plugin review request library

classes/PublishPress/Permissions/UI/Dashboard/DashboardFilters.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/Users.php
=> Invalid configuration UI on multisite

classes/PublishPress/Permissions/DB/Groups.php
New filter "presspermit_is_authenticated_user"
Fixes #79
=> Add a PHP filter for {Authenticated} Permission Group membership

classes/PublishPress/Permissions/DB/Migration.php, classes/PublishPress/Permissions/PluginUpdated.php, classes/PublishPress/Permissions/UI/Handlers/Settings.php
=> Pro: Enable Teaser module by default

classes/PublishPress/Permissions/UI/SettingsAdmin.php, common/css/presspermit.css, common/css/presspermit.less
Related to #354 #468
Complements https://github.com/publishpress/PublishPress-Permissions-Pro/pull/319
=> Teaser new settings UI review

classes/PublishPress/Permissions/UI/Settings.php, classes/PublishPress/Permissions/UI/SettingsTabModules.php, common/css/settings.css, includes/CoreAdmin.php, includes/SettingsTabInstall.php
Modules becomes the default tab.
=> Separate tabs for modules, license

classes/PublishPress/Permissions/UI/Dashboard/PluginAdmin.php
=> Remove installation welcome notice

modules/presspermit-collaboration/classes/Permissions/Collab/AdminFilters.php
=> Post preview doesn't display unsaved changes

classes/PublishPress/Permissions/UI/AgentPermissionsUI.php
=> Pro: bbPress - Specific Permissions unselectable on Edit Permissions screen

classes/PublishPress/Permissions.php
https://github.com/publishpress/PublishPress-Permissions/issues/788
=> Pro: Smart Plugin Manager conflict causes fatal errors

classes/PublishPress/Permissions/PermissionsAdmin.php
=> Edit Group Permissions: no label for stored Nav Menu Manager role

modules/presspermit-collaboration/classes/Permissions/Collab/AdminWorkarounds.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/NavMenu.php
=> Nav Menu Manager role does not enable menu creation

classes/PublishPress/Permissions/PageFilters.php
=> get_pages() call - use IN clause to prevent excessively large query

classes/PublishPress/Permissions/UI/SettingsAdmin.php, classes/PublishPress/Permissions/UserGroupsUpdate.php
=> Network-wide option storage fails on installs where main site ID is not 1

classes/PublishPress/Permissions/PermissionsAdmin.php
=> Permissions Admin: Supplemental role title displayed redundantly in some configurations

modules/presspermit-collaboration/classes/Permissions/Collab/Revisions/Admin.php
=> Limiting revision creation to specific posts also blocked reading of other posts

modules/presspermit-collaboration/classes/Permissions/Collab/NavMenus.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/NavMenu.php
=> Nav Menu Management by Limited Users: menu items removed under some conditions

press-permit-core.php, readme.txt
=> Plugins Screen: Note that free plugin can be deleted after Pro activation

classes/PublishPress/Permissions.php
=> PHP 8.1: Notice in wp-admin

classes/PublishPress/Permissions/ErrorNotice.php, classes/PublishPress/Permissions/UI/Dashboard/DashboardFilters.php, functions.php, modules/presspermit-collaboration/classes/Permissions/Collab/AdminFilters.php, modules/presspermit-collaboration/classes/Permissions/Collab/Compat/BakeryPageBuilder.php
=> Fatal error in wp-admin if certain request variables have unexpected values

classes/PublishPress/Permissions/PostFilters.php
=> PublishPress Planner: Status Change notifications not sent

classes/PublishPress/Permissions/UI/AgentExceptionsAjax.php, classes/PublishPress/Permissions/UI/AgentPermissionsUI.php, classes/PublishPress/Permissions/UI/SettingsTabCore.php, modules/presspermit-collaboration/classes/Permissions/Collab/AdminFilters.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/AjaxUI.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
=> Clarify admin labels to distinguish Navigation Block Menus from legacy Nav Menus

classes/PublishPress/Permissions.php
=> Serialization error causes REST API to fail

classes/PublishPress/Permissions/UI/Handlers/AgentEdit.php
=> Specific Permission for Editing posts with Private visibility not saved correctly

classes/PressShack/LibWP.php, classes/PublishPress/Permissions/TermFilters.php, classes/PublishPress/Permissions/UI/Dashboard/DashboardFilters.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php, modules/presspermit-collaboration/classes/Permissions/CollabHooksAdminNonAdministrator.php
Also add a helper function for admin url construction / analysis
=> Terms filtering: adjust context detection

modules/presspermit-collaboration/classes/Permissions/CollabHooksCompat.php
This is a temporary workaround, forcing Polylang to apply the 'get_pages' filter as before. Modifying Permissions' page filtering to use query filtering instead of results filtering will require some development and test time.
Fixes #947
=> Polylang + WP 6.3: Language filter no longer applied to Page Parent dropdown

classes/PublishPress/Permissions/UI/AgentPermissions.php
=> Edit User Permissions: PHP Warning "compact(): Argument must be string..."

modules/presspermit-collaboration/classes/Permissions/Collab/PostTermsSave.php
=> Filtering of default category / term by other plugin is overridden

classes/PublishPress/PermissionsHooks.php
=> Fatal error "Call to a member function init() on null" under some configs

modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
=> Collorative Publishing module is not loaded on some installations

classes/PublishPress/Permissions/PostFilters.php
=> Beaver Builder: Some queries in BB shortcodes are improperly filtered

modules/presspermit-collaboration/classes/Permissions/Collab/PostTermsSave.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
=> On Post edit, Tags not filtered based on Specific Permissions

classes/PublishPress/Permissions/UI/Dashboard/UsersListing.php
=> Users Screen: bbPress Forum Role column is hidden

modules/presspermit-collaboration/classes/Permissions/Collab/PostSaveHierarchical.php
=> Subpage update causes fatal error

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/PostFilters.php, classes/PublishPress/PermissionsUser.php, modules/presspermit-collaboration/classes/Permissions/Collab/PostFilters.php
=> PublishPress Capabilities: Negated caps not properly applied under some Permissions configs

classes/PublishPress/Permissions/CapabilityFilters.php
=> Google Analytics by MonsterInsights: custom field error message on post update

classes/PublishPress/Permissions/PostFilters.php
=> PublishPress Revisions: Apply restrictive Submit Revision permissions to Revision Queue listing

includes/CoreAdmin.php
=> One error message was not translated

classes/PublishPress/Permissions/UI/AgentPermissions.php, classes/PublishPress/Permissions/UI/AgentPermissionsUI.php, classes/PublishPress/Permissions/UI/Groups.php, classes/PublishPress/Permissions/UI/GroupsListTable.php, includes/promo/posts-teaser-promo.php, includes/promo/statuses-promo.php, includes/promo/sync-promo.php, includes/promo/visibility-statuses-promo.php
Fixed text domain in promo php files
=> Fixed text domain in promo php files

modules/presspermit-collaboration/classes/Permissions/Collab/UI/SettingsTabEditing.php
=> Plugin settings: Media Library checkbox not displayed under some conditions

classes/PressShack/LibWP.php
=> Disable Gutenberg plugin: Classic Editor mode not detected

classes/PublishPress/Permissions/UI/Dashboard/UsersListing.php
=> Admin Columns plugin: Users listing inappropriately filtered

classes/PublishPress/PermissionsHooksAdmin.php
=> Fatal error if constant SSEO_VERSION is unexpectedly defined

classes/PublishPress/Permissions/PostFilters.php
Teaser + PostX Grid Blocks: Ajax post scrolling failed for non-Editors
=> Adjust Teaser API for plugin compat

classes/PublishPress/Permissions/UI/AgentsDynamicUI.php
=> PublishPress Revisions: Can't add Administrators to Change Request Notification group

classes/PublishPress/Permissions/DB/DatabaseSetup.php
Fixes #1130
Add unique key to pp_group_members table, for new installations only.
=> DB Schema: add unique key to pp_group_members

classes/PublishPress/PermissionsHooks.php
If a restricted user adds an Event Category, the term hierarchy cache is updated to an empty array, breaking subsequent Event Category requests.
Fixes #1137
=> Events Manager: Corruption of event hierarchy after restricted user adds Event Category

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/UI/SettingsTabCore.php
=> PublishPress Series: Specific Permissions could not be assigned for Series Categories

modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
=> Fatal error on category / term insertion (WordPress < 6.1)

classes/PublishPress/Permissions/ItemSave.php
=> Specific Permissions not propagated to new subpages

classes/PublishPress/Permissions/UI/AgentPermissions.php
Fix: Made string translatable in AgentPermissions.php file
=> Fix: Made string translatable in AgentPermissions.php file

classes/PublishPress/Permissions/UI/AgentsAjax.php
=> Permissions Metabox User Search: Search user_email field

classes/PublishPress/PermissionsUser.php
=> PublishPress Authors - Default author inappropriately applied for Contributors / Authors under some configurations

classes/PublishPress/PermissionsHooks.php
=> The Events Calendar: Error on event category creation if no others exist

classes/PublishPress/Permissions/ItemSave.php, classes/PublishPress/Permissions/PostSave.php
=> Updating a page causes propagated permissions to be cleared under some configs

classes/PublishPress/Permissions/PostSave.php
=> Permissions metabox value not saved

classes/PublishPress/Permissions/Capabilities.php
=> Fatal error under some conditions if a post type is registered abnormally

classes/PublishPress/Permissions/CapabilityFiltersAdmin.php
=> PHP Warning in post editor under some site configurations

classes/PressShack/LibWP.php, classes/PublishPress/Permissions/PostFilters.php, classes/PublishPress/Permissions/TermQuery.php
=> PublishPress Authors: Poor query performance on highly populated sites

classes/PublishPress/Permissions/PostFilters.php, classes/PublishPress/Permissions/PostFiltersExtra.php
=> Multisite: Posts query error on installs with abnormal site switching / caching

modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
=> Multisite + PHP 8.2: Fatal error on sub-sites created prior to Permissions install

classes/PublishPress/Permissions/REST.php
=> Non-Administrators cannot add new post on some sites

classes/PublishPress/Permissions/DB/DatabaseSetup.php
=> Plugin activation causes unexpected output on some servers

classes/PublishPress/Permissions/UI/Handlers/Groups.php
=> PHP Notice when deleting a group

classes/PublishPress/Permissions/PostFilters.php
=> Object cache Race Condition in mapMetaCap

classes/PublishPress/Permissions/Constants.php, classes/PublishPress/Permissions/UI/AgentsAjax.php, classes/PublishPress/Permissions/UI/AgentsDynamicUI.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/PostEdit.php
=> Pro: Group membership selection allows Administrators if Access Circles active

classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsData.php, classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsRenderUI.php
=> Add New Post: Wrong defaults in Permissions metabox under some configurations

classes/PublishPress/Permissions/CapabilityFilters.php
=> Revisions Compat: Support reduced filtering for certain use cases

modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/Admin.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisions/Admin.php
=> "Limit to" permissions for Revision Submission also block draft post editing

classes/PublishPress/Permissions/CapabilityFilters.php
=> PHP Warning for undefined variable $item_status

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/PostFiltersFront.php, classes/PublishPress/Permissions/UI/SettingsAdmin.php, classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php
=> Apply Category restrictions to Category archive page

classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsRenderUI.php
=> Remove the ( ) from editor metaboxes

classes/PublishPress/Permissions/TermFilters.php
=> ACF Taxonomy Field does not include subcategories

modules/presspermit-collaboration/classes/Permissions/Collab/PostTermsSave.php
=> On Post update, numerically-named category created

classes/PublishPress/Permissions/CapabilityFilters.php
=> Edit Page: Fatal error with some third party plugins

classes/PublishPress/Permissions/UI/SettingsTabCore.php
Closes #1248
Clean up screen by combining this caption with general note about Filtered Post Types settings.
=> create_posts setting: Direct users to PP Capabilities

classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsUI.php
=> If Everyone meta role is blocked, reflect that in each role's "default" caption

classes/PublishPress/Permissions/DB/DatabaseSetup.php, classes/PublishPress/Permissions/PluginUpdated.php
=> Duplicate WP Role groups on install

classes/PublishPress/Permissions/UI/AgentPermissionsUI.php, classes/PublishPress/Permissions/UI/Groups.php, classes/PublishPress/Permissions/UI/HintsItemExceptions.php, classes/PublishPress/Permissions/UI/HintsMedia.php, classes/PublishPress/Permissions/UI/HintsPostEdit.php, classes/PublishPress/Permissions/UI/SettingsAdmin.php, classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php, classes/PublishPress/Permissions/UI/SettingsTabCore.php
=> Settings screen: shorten / improve some hint captions

classes/PublishPress/Permissions/UI/AgentPermissionsUI.php
=> Change tooltip text

common/css/edit-permissions.css, common/css/edit-permissions.less
This is to reduce a spacing change I made yesterday.
=> Permission notes: tighten spacing slightly

classes/PublishPress/Permissions/UI/AgentPermissionsUI.php, common/css/edit-permissions.css, common/css/edit-permissions.less
=> Edit Permissions: Caption item edit links with item type label

classes/PublishPress/Permissions/UI/AgentPermissionsUI.php
=> Adjust display criteria for Fix Sub-Page Permissions link

classes/PublishPress/Permissions/UI/AgentPermissions.php, classes/PublishPress/Permissions/UI/AgentPermissionsUI.php, languages/press-permit-core.pot, press-permit-core.php, readme.txt
= 4.2.1 - 2 May 2025 =
* Fixed: Group Permissions on the Edit User screen now display with the correct formatting. #1601  
* Fixed: Resolved an uncaught error that occurred on the Edit Group screen under certain conditions. #1598
=> Release 4.2.1

classes/PublishPress/Permissions/UI/AgentPermissionsUI.php
Change the caption from "All Statuses" to "All Post Types"
#1559
=> Add Permissions: fix caption in Post Type dropdown element

common/css/edit-permissions.css
=> Edit Permission Group - Reduce whitespace around group membership selector

composer.json, composer.lock, lib/composer.lock, lib/vendor/composer/installed.php
- change `-pre-autoload-dump` to `pre-autoload-dump`
- change `-pre-update-cmd` to `pre-update-cmd`
- change `-pre-install-cmd` to `pre-install-cmd`
- composer update
=> update composer.json & composer update

classes/PublishPress/Permissions/UI/Dashboard/DashboardFilters.php, common/css/presspermit.css, common/css/presspermit.less
Fixed https://github.com/publishpress/PublishPress-Permissions/issues/1618
=> Add edit sub menu

classes/PublishPress/Permissions/UI/SettingsAdmin.php
=> Remove documentation of pp_define_moderation capability from non-legacy code

classes/PublishPress/Permissions/DB/DatabaseSetup.php
=> Create pp_group_members table with primary key on new installations

classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php, classes/PublishPress/Permissions/UI/SettingsTabCore.php, classes/PublishPress/PermissionsHooksAdmin.php, modules/presspermit-collaboration/classes/Permissions/CollabHooksAdmin.php
=> Drop Capabilities list from Settings > Advanced; use cme_capability_descriptions filter

classes/PublishPress/Permissions/UI/SettingsAdmin.php
=> Update capability descriptions for display on PP Capabilities tab

classes/PublishPress/Permissions/UI/Dashboard/DashboardFilters.php, classes/PublishPress/Permissions/UI/SettingsAdmin.php, classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php, common/css/settings.css
Also make the link visible even without "display all advanced settings" enabled.
=> Update captions for Permissions > Settings > Advanced link to CME

classes/PublishPress/PermissionsHooks.php
=> Error on event category creation

common/css/presspermit.css, modules/presspermit-collaboration/classes/Permissions/Collab/UI/RoleUsage.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/RoleUsageHelper.php
=> Adjust Edit Role Usage captions, margins

modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/DashboardFilters.php
=> Keep Role Usage menu item available with Role Usage Edit screen

classes/PublishPress/Permissions/TermSave.php
=> BasePress: Specific Permissions are not propagated to Sub-categories

classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsRenderUI.php, classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsUI.php
Fixed https://github.com/publishpress/PublishPress-Permissions/issues/1642
=> Update small text in metabox

classes/PublishPress/Permissions/UI/Groups.php, classes/PublishPress/Permissions/UI/GroupsListTable.php, classes/PublishPress/Permissions/UI/GroupsQuery.php, classes/PublishPress/Permissions/UI/PluginPage.php, classes/PublishPress/Permissions/UI/UsersListTable.php, common/css/presspermit.css, common/css/presspermit.less, includes/css/settings.css
Fixed https://github.com/publishpress/PublishPress-Permissions/issues/1367
=> Add Users tab to Permission List

classes/PublishPress/Permissions/UI/AgentPermissions.php, classes/PublishPress/Permissions/UI/AgentPermissionsUI.php, classes/PublishPress/Permissions/UI/Dashboard/DashboardFilters.php, classes/PublishPress/Permissions/UI/Dashboard/Profile.php, classes/PublishPress/Permissions/UI/Dashboard/UsersListing.php, classes/PublishPress/Permissions/UI/GroupNew.php, classes/PublishPress/Permissions/UI/Groups.php, classes/PublishPress/Permissions/UI/GroupsListTable.php, classes/PublishPress/Permissions/UI/GroupsListTableBase.php, classes/PublishPress/Permissions/UI/GroupsQuery.php, classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php, classes/PublishPress/Permissions/UI/UsersListTable.php, common/css/edit-permissions.css, common/css/edit-permissions.less
Fixed https://github.com/publishpress/PublishPress-Permissions/issues/1367
=> feat-1367-add-filter-tab-users

classes/PublishPress/Permissions/UI/Groups.php, classes/PublishPress/Permissions/UI/GroupsListTable.php, classes/PublishPress/Permissions/UI/GroupsQuery.php, classes/PublishPress/Permissions/UI/PluginPage.php, classes/PublishPress/Permissions/UI/UsersListTable.php, common/css/presspermit.css, common/css/presspermit.less
Fixed :
- https://github.com/publishpress/PublishPress-Permissions/issues/1699
- https://github.com/publishpress/PublishPress-Permissions/issues/1700
=> fix-1699-table-column-order

classes/PublishPress/Permissions/Admin.php, classes/PublishPress/Permissions/UI/SettingsTabCore.php
=> Remove the "Display PublishPress Branding in Admin"

classes/PublishPress/Permissions/CommentFilters.php
=> WooCommerce: Database query error on Products screen

common/css/edit-permissions.css, common/css/edit-permissions.less
=> Rename placeholder datepicker and improve button UI Memberships

common/css/settings.css, common/css/settings.less
=> Update Settings style to match Future

classes/PublishPress/Permissions/UI/SettingsTabFileAccess.php, classes/PublishPress/Permissions/UI/SettingsTabMembership.php
=> Adjust promo captions for Membership, File Access tabs

classes/PublishPress/Permissions/UI/SettingsTabFileAccess.php, classes/PublishPress/Permissions/UI/SettingsTabMembership.php, common/css/settings.css, common/css/settings.less
=> FIx button style

modules/presspermit-collaboration/classes/Permissions/Collab/REST_Workarounds.php
=> Private series_grouping value in "getEnabledPostType()" with no data causes null error in REST_Workarounds

classes/PublishPress/Permissions/UI/AgentsDynamicUI.php
=> Fix conflict lib select2 with other plugin

classes/PublishPress/Permissions/MediaFilters.php
=> Fix Possible warning/error due to fake postID

classes/PublishPress/Permissions/UI/SettingsTabIntegrations.php, classes/PublishPress/Permissions/UI/SettingsTabMembership.php, includes/CoreAdmin.php
=> Rename Premium to Pro

classes/PublishPress/Permissions/UI/AgentPermissionsUI.php, common/css/settings.css, common/css/settings.less
=> Inconsistent Pro upgrade nudges

classes/PublishPress/Permissions/UI/SettingsTabMembership.php
=> Remove Learn more link

classes/PublishPress/Permissions/UI/SettingsTabIntegrations.php
=> Numbers on the Revisions tab

classes/PublishPress/Permissions/DB/Permissions.php, classes/PublishPress/Permissions/UI/Dashboard/ItemAjax.php, classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsRenderUI.php, classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsUI.php, classes/PublishPress/PermissionsHooks.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisions/CapabilityFilters.php
=> Hotfix 1836 permissions not applied to revisions

modules/presspermit-collaboration/classes/Permissions/Collab/UI/SettingsTabEditing.php
=> Update captions and descriptions for file-related permissions in editing settings

classes/PublishPress/Permissions/DB/Permissions.php
=> Conflict with Statuses plugin causes out of memory error on login

classes/PublishPress/Permissions/UI/SettingsTabModules.php, common/css/settings.css, common/css/settings.less, composer.lock, includes/CoreAdmin.php, languages/press-permit-core.pot, lib/vendor/composer/installed.php
=> Adjust design card in tab Feature with capabilities

classes/PublishPress/Permissions/UI/Dashboard/Profile.php, classes/PublishPress/Permissions/UI/Dashboard/UsersListing.php, classes/PublishPress/Permissions/UI/Groups.php, classes/PublishPress/Permissions/UI/GroupsListTableBase.php, classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php, classes/PublishPress/Permissions/UI/UsersListTable.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/SettingsTabEditing.php
=> Fixed Text Domain

common/css/settings.css
=> Widen license key input box to support long key

readme.txt
=> Update Readme file (#1903)

classes/PublishPress/Permissions/UI/SettingsTabModules.php, common/css/settings.css, common/css/settings.less, includes/CoreAdmin.php
=> Adjust Features text

classes/PublishPress/PermissionsHooks.php
=> PublishPress Statuses: List capabilities ineffective if post requires status-specific editing capabilities

classes/PublishPress/Permissions/UI/SettingsTabUserPages.php
=> Promo text update for User Pages

press-permit-core.php
=> GiveWP access failure
