includes/SettingsTabInstall.php
Settings > Install caption about restoring a Press Permit Pro 2.6.x installation, even if none was installed. Since version 3.0.
This occurred due to the Collaborative Publishing module being moved into Free.
=> Settings > Install: invalid Press Permit Pro 2.6.x migration caption

classes/PublishPress/Permissions/DB/Permissions.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/Admin.php
Fixes #107
* Fixed : Restrictive term-specific Permissions were not correctly negated by permissive term-specific restrictions assigned to another role or group for the same user
* Compat : Revisions - Revision Permissions assigned for specific categories did not enable editing of existing revisions
=> Term-specific Permissions ineffective in some configurations

classes/PublishPress/Permissions/UI/SettingsTabCore.php
Leave the new list_posts capability support as an undocumented feature until Capabilities is updated to provide a configuration UI.
=> Settings > Core: remove Admin Ready-Only caption for now

common/js/presspermit.dev.js, common/js/role-edit.dev.js, modules/presspermit-collaboration/common/js/post-edit.dev.js
=> WP 5.5: Remove old comments to avoid false alarms for .live() usage

modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/PostsListingNonAdministrator.php
WP Cache was cleared on wp-admin Pages access by non-Administrator.
=> Excessive clearing of WP Cache

classes/PressShack/LibWP.php
Classic Editor plugin - Block editor usage was not properly detected if user selection of default editor is enabled and set to Block
=> Classic Editor plugin - block editor not detected in some configurations

classes/PublishPress/Permissions/UI/Dashboard/TermsListing.php
Term managers who are limited (through "include" exceptions) to managing a fixed set of terms had "None" category listed in Parent dropdown, even though they cannot add a top-level category.
=> Admin Categories screen: Parent "None" filtering

modules/presspermit-collaboration/classes/Permissions/CollabHooksAdmin.php
Enable Permissions filtering, but disable Quick Edit and Context Menu for non-Administrators by default.
Available constants:
PP_NESTED_PAGES_DISABLE_FILTERING, PP_NESTED_PAGES_QUICKEDIT_ROLES, PP_NESTED_PAGES_CONTEXT_MENU_ROLES
=> Nested Pages: basic filtering, with limitations

classes/PressShack/LibWP.php
The Woo admin_ajax query for this operation passes product_id, but no post_id.
Fixes #182
=> WooCommerce: Cannot add new Product Variation

classes/PublishPress/Permissions/DB/Permissions.php
Fixes #187 
Post access was improperly blocked under some configurations if Permissions > Settings > Core > "Post-specific Permissions take priority" enabled.
The version 3.3.3 release fixed the non-application of this setting, which prevented intended post-level blockages from overriding term-level allowances as intended.  However, the change applied the restrictions too broadly.   The original (pre-3.3.3) application of this setting to the query clauses included some inconsistency and convolution.  However, a new constant PP_LEGACY_POST_BLOCKAGE is now available to fully restore the pre-3.3.3 behavior.
Constant PP_RESTRICTION_PRIORITY continues to serve a different purpose (now more consistently applied): override post-level allowances with post-level blockages, and override term-level …
=> Post access improperly blocked under some configurations

modules/presspermit-collaboration/classes/Permissions/CollabHooksCompat.php
With "control custom statuses" enabled and custom capabilities enabled for a workflow status, the checkboxes for those capabilities were not displayed to Administrators under some configurations.  This occurred only if the Administrator role had the pp_moderate_any capability added.
=> Capabilities Pro: checkboxes for status capabilities not displayed

classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsUI.php
Change the "No access customizations stored" caption. Fixes #207
=> Friendlier caption in Permissions metaboxes

modules/presspermit-collaboration/classes/Permissions/Collab/CapabilityFilters.php
On new post creation, Revisors have Submit button replaced by a Publish button, which fails. The only way to submit a new post is to Save Draft first. Fixes #219
=> Revisions: On post-new, Revisors get failing Publish button

modules/presspermit-collaboration/classes/Permissions/Collab/CapabilityFilters.php
Users who have been granted editing access for pages (or some other post type) cannot embed blocks if they lack the edit_posts capability. This is a function of the WP core post type, capability and role definitions. Let's make it more consistent by accepting the upload_files capability as an alternate criteria.
Also provide new filter 'presspermit_embed_capability' to customize this alternate capability check.
Fixes #225
=> Users lacking edit_posts capability cannot embed Gutenberg blocks

modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/Admin.php
If Revisors are blocked from editing other users' drafts, those drafts should be listed (but unclickable) if the Revisor role has the list_others_pages capability (or equivalent for the post type).
Fixes #238
=> Revisions integration: list_others_pages for Revisors

classes/PublishPress/Permissions/CommentFilters.php
Don't strip out the ORDER BY clause unless there is both a GROUP BY clause and a COUNT field.  Also support override by constant PRESSPERMIT_LEGACY_COMMENT_FILTERING
=> ODBC comment query: safeguard against misapplication

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/TermFiltersCount.php, classes/PublishPress/Permissions/UI/SettingsTabCore.php
The code already supports constant PP_UNFILTERED_TERM_COUNTS to disable TallyTermCounts() execution, saving some extra db queries.  This new setting exposes this performance enhancement for the general user base, now that term counts are less commonly displayed.
With the setting enabled, TallyTermCounts is executed only on wp-admin/edit-tags.php
=> New Front End setting "Performance: Don't filter category / tag counts"

classes/PublishPress/PermissionsUser.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/ContentRoles.php
Pending Revision Monitors group members were not properly filtered for editing access prior to display as available "Publishers to Notify"
Fixes #267
=> PublishPress Revisions: Monitors group not filtered for "Publishers to Notify" UI

modules/presspermit-collaboration/classes/Permissions/Collab/CapabilityFiltersAdmin.php
If third party filtering adds an edit_theme_options capability requirement to some other capability requirement, Nav Menu filtering is incorrectly applied, causing improperly blocked access.
=> Access blocked if edit_theme_options capability required by other plugin

classes/PublishPress/Permissions/PostFilters.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/Admin.php
Contributors can't edit their own drafts if PublishPress Revisions is active and has its plugin settings configured to "Editing others' revisions requires role capability"
This is not a new bug stemming from recent releases -- just newly discovered.
=> Revisions: Contributors can't edit own drafts

classes/PublishPress/Permissions/UI/Agents.php, classes/PublishPress/Permissions/UI/Dashboard/Profile.php
This UI modification is currently enabled by the following constants:
PRESSPERMIT_ADD_USER_SINGLE_GROUP_SELECT
PRESSPERMIT_EDIT_USER_SINGLE_GROUP_SELECT
=> Support Permission Group single select (radio) on Add/Edit User

classes/PublishPress/Permissions/PostFilters.php
This was observed on one site which loaded other posts on the home page. Also affected menu item display.
Fixes #298
=> Anonymous visitors blocked from viewing public posts under some conditions

modules/presspermit-collaboration/classes/Permissions/Collab/UI/RoleUsage.php
This anticipates possible future implementation of the hints icon on screens other than Settings.
=> Role Usage screen: mark a section as non-hidable

classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsUI.php, classes/PublishPress/Permissions/UI/Groups.php
Use either "Roles" or "WordPress Roles"
=> Eliminate "WP" prefix from Roles label

classes/PublishPress/Permissions/PostFilters.php
Activation of the Authors plugin was found to trigger this conflict on a test site.
Fixes #364
=> WP_Privacy_Policy change check interferes with map_meta_cap filtering

classes/PressShack/LibWP.php
The PHP warning occurs if with the Classic Editor plugin active if users are allowed to select their editor.
Fixes #375
=> Classic Editor plugin: PHP warning for undefined variable current_user on some screens

modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/PostFilters.php
This access issue occurs even if they are listed in Revision Queue (also requires PublishPress Revisions 2.5.1)
Fixes #377
=> Revisions: Revisors could not preview other users' pending revisions

modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/Admin.php
This fix also requires Revisions 2.5.3
Fixes #379
=> PublishPress Revisions - Pending Revision Monitors group ineffective

modules/presspermit-collaboration/classes/Permissions/Collab/UI/Dashboard/PostEdit.php
=> Classic Editor: Publish metabox replaced "Public" caption with blank space

classes/PressShack/LibWP.php
=> Gutenberg Ramp: Fatal error on editor screen if PublishPress Revisions not active

modules/presspermit-collaboration/classes/Permissions/Collab/Revisionary/ContentRoles.php
The Pending Revision Monitors group fails to control Revision submission notifications when first installation of Permissions was version 3.5 or later.
Fixes #401
=> Revisions: Pending Revision Monitors group ineffective for new installations

classes/PublishPress/PermissionsHooks.php
Fixes #449
Work around HTML Forms plugin calling admin-ajax.php and async-upload.php with no action argument.
Replaces #446
Replaces #447
Issues cited by https://github.com/network-rail
=> HTML Forms plugin: PHP Notice on form submission / file upload

modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
Fixes #449
Work around HTML Forms plugin calling admin-ajax.php with no action argument.
Replaces #447
Issues cited by https://github.com/network-rail
=> HTML Forms plugin: PHP Notice on form submission

modules/presspermit-collaboration/classes/Permissions/Collab/UI/SettingsTabEditing.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
In our current implementation, configuring a post type (through Permissions > Settings > Editing) for a default custom privacy without locking that privacy results in inconsistent results (lock requirement applied in Gutenberg JS regardless of setting).  Work around this by forcing the lock setting for any post type that uses Gutenberg.
This applies to Pro installations using the Status Control module.
=> Pro API: In current Gutenberg integration, custom default privacy requires lock

modules/presspermit-collaboration/classes/Permissions/Collab/UI/Gutenberg/PostEdit.php
The error occurred for non-Editors when attempting to re-caption the Publish button
=> Gutenberg plugin: javascript error in editor

common/css/presspermit.css
Edit User screen - Permissions box styling was broken if custom styling is applied to certain standard WP classes
=> Edit User screen - Permissions box styling

modules/presspermit-collaboration/classes/Permissions/Collab/Revisions/CapabilityFilters.php
Limited revisors could not edit newly created revision under some Permissions configurations
=> Revisions integration - revision creation by limited revisors

classes/PublishPress/Permissions/PostFilters.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisions/Admin.php, modules/presspermit-collaboration/classes/Permissions/Collab/Revisions/PostFilters.php
If Revisions > Settings > "Prevent Revisors from editing other user's drafts" is enabled, Contributors can't edit their own draft posts.
Fixes #528
=> Revisions: Contributors can't edit own draft posts in some configurations

classes/PublishPress/Permissions/UI/Dashboard/UsersListing.php
Fixes #532
Deprecated: Required parameter $column_name
=> PHP 8: Warning on Users screen

classes/PublishPress/Permissions/ErrorNotice.php, classes/PublishPress/Permissions/UI/ItemsMetabox.php
there is no `presspermit_isset_REQUEST` definition
```
$ git log | head -3
commit d4530ab79e9a14733180382d1a2b5045e1347757 (HEAD -> refs/heads/master, refs/remotes/origin/master, refs/remotes/origin/HEAD)
Merge: 942c121 3004f04
Author: Kevin Behrens <43488774+agapetry@users.noreply.github.com>
$ grep -r presspermit_isset_REQUEST
classes/PublishPress/Permissions/UI/ItemsMetabox.php:        $pagenum = $current_tab && presspermit_isset_REQUEST('paged') ? absint(presspermit_REQUEST_var('paged')) : 1;
classes/PublishPress/Permissions/ErrorNotice.php:                $args = (presspermit_isset_REQUEST('page') && (0 === strpos(presspermit_REQUEST_key('page'), 'presspermit-')))
```
probably, it should be replaced with `presspermit_is_REQUEST`
=> fix typo: presspermit_isset_REQUEST() -> presspermit_is_REQUEST()

press-permit-core.php
when we call `presspermit_err('rs_active')` at line 103, we run 
```
case 'rs_active':
define('PRESSPERMIT_DISABLE_QUERYFILTERS', true);
$args = (presspermit_is_REQUEST('page') && (0 === strpos(presspermit_REQUEST_key('page'), 'presspermit-')))
? ['style' => 'color:black']
: [];
```
from classes/PublishPress/Permissions/ErrorNotice.php but `presspermit_is_REQUEST()` and `presspermit_REQUEST_key()` are not declared yet, so i propose to move `require_once(__DIR__ . '/functions.php')` above the condition to fix this issue and avoid similar issues later
=> Fatal error on some error notifications

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/Capabilities.php, classes/PublishPress/Permissions/CapabilityCaster.php, classes/PublishPress/Permissions/CapabilityFilters.php, classes/PublishPress/Permissions/PostFilters.php, classes/PublishPress/Permissions/RoleDefaults.php, classes/PublishPress/Permissions/Roles.php, classes/PublishPress/Permissions/UI/AgentRolesAjax.php, classes/PublishPress/PermissionsUser.php, modules/presspermit-import/classes/Permissions/Import/DB/RoleScoper.php, press-permit-core.php
Migrate to internal use of 'read_public' capability to regulate read access to publicly published posts / pages.  By implicitly assigning this capability instead of 'read' capability, roles are not forced into dashboard access.
Fixes #649
=> Stop implicitly assigning read capability

classes/PublishPress/Permissions/Capabilities.php, classes/PublishPress/Permissions/CapabilityFilters.php, press-permit-core.php
The read_public solution (allowing the read capability to be removed from roles to block dashboard access without making public posts unreadable) can still be activated by the following constant definition:
define('PRESSPERMIT_READ_PUBLIC_CAP', 'read_public');
=> Revert default read_public capability definition

classes/PublishPress/Permissions/REST.php
=> Category Permissions: Assign Category restrictions don't prevent checkbox display in Gutenberg

modules/presspermit-collaboration/classes/Permissions/Collab/Revisions/CapabilityFilters.php
Category-specific revision creation or submission revisions fail if term_id is different from term_taxonomy_id.
=> Revisions: Category-specific submission permissions fail on some sites

classes/PublishPress/Permissions/TermFilters.php
=> Category Management restrictions don't exclude unmanagable terms from listing

classes/PublishPress/Permissions/PluginUpdated.php, classes/PublishPress/Permissions/UI/Dashboard/TermsListing.php, classes/PublishPress/PermissionsHooks.php, modules/presspermit-collaboration/classes/Permissions/Collab/CapabilityFiltersAdmin.php
The {$taxonomy}_children arrays stored to the options table normally interrupt term filtering.  Instead of forced clearance of these stored values, filter "option_{$taxonomy}_children".
Also fix version comparison logic that triggers update scripts. It was executing needlessly when running Permissions [Free] if an older version of Pro was previously installed.
Fixes #456
=> Restore {$taxonomy}_children option storage

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php, common/css/presspermit.css, common/css/presspermit.less, common/css/settings.css, uninstall.php
Closes #702
Note that plugin settings and configuration data are only deleted upon deletion of the last copy of Permissions / Permissions Pro.  Plugin deletion will have no effect if another copy of the plugin remains in the plugins folder (even if it's not activated).
=> Add a "Remove data on uninstall" option

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/UI/SettingsAdmin.php, classes/PublishPress/Permissions/UI/SettingsTabCore.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/SettingsTabEditing.php, modules/presspermit-collaboration/classes/Permissions/Collab/Updated.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
If this setting is enabled, implicitly add list_others_posts capability for each post type where the user has the basic editing capability.  This achieves the goal of defaulting to WP core behavior for the Posts / Pages listing.
For existing installations, store this setting false to maintain current listing behavior.
Also rearrange the Settings > Editing sections and improve hint captions for better clarity.
=> List others' uneditable posts by default; setting on Editing tab

classes/PublishPress/PermissionsUser.php
Pull this influential setting directly from get_site_option() to ensure it's not treated as a regular option.
=> Extra safeguard to ensure network-wide group activation

uninstall.php
This error occurs on single site installations due to the plugin calling a multisite function.
Fixes #780
=> Advanced option "Delete settings on plugin deletion" fails

classes/PublishPress/Permissions/UI/Dashboard/TermEdit.php
Remove extra update button for non-Administrators who don't have multiple Specific Permission metaboxes.
Fixes #794
=> Redundant update button and associated text on categories page

classes/PublishPress/Permissions/ItemSave.php, modules/presspermit-collaboration/classes/Permissions/Collab/CapabilityFiltersAdmin.php, modules/presspermit-collaboration/classes/Permissions/Collab/PostSaveHierarchical.php
Limited authors may be locked out of editing new page if access depends on inheriting specific permissions from a required parent page.
Fixes #804
=> Classic Editor: Limited authors may be locked out of editing new page

modules/presspermit-collaboration/classes/Permissions/Collab/CapabilityFiltersAdmin.php, modules/presspermit-collaboration/classes/Permissions/Collab/PostSaveHierarchical.php
Support the following constants to mitigate any unexpected effects:
define('PRESSPERMIT_NO_PROCESS_BEFORE_REDIRECT', true); define('PRESSPERMIT_NO_PROCESS_BEFORE_PARENT_REVERT', true);
=> Precaution: constants to disable new permission inheritance processes

modules/presspermit-collaboration/classes/Permissions/Collab/CapabilityFiltersAdmin.php, modules/presspermit-collaboration/classes/Permissions/Collab/UI/SettingsTabEditing.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
Adds a new setting: Permissions > Settings > Editing > Media Library > "Prevent editing uploads if attached to a non-editable post"
This defaults to true as with previous versions.
The new setting is only available if the following setting is enabled: Permissions > Settings > Core > Filtered Post Types > "Enforce distinct edit, delete capability requirements for Media"
Fixes #861
=> Media Library: Option to control attachment editing access separately from parent post editing access

classes/PublishPress/Permissions/PostFilters.php
=> WPML: 404 error for Home Page request by logged in user if post type not enabled for filtering

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/CapabilityCaster.php, classes/PublishPress/Permissions/PluginUpdated.php, classes/PublishPress/Permissions/UI/SettingsAdmin.php, classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php
Fixes #939
Introduce a new Advanced setting to default to existing behavior on sites that already have supplemental roles assigned.
=> Supplemental Role assigned for a specific post type grants many unrelated capabilities

classes/PublishPress/PermissionsHooks.php, includes/SettingsTabInstall.php
Prevent Core update scripts from being skipped when a Pro package is installed for the first time.
Also prevent hypothetical installation scripts in Pro modules from being skipped if a Pro package is installed for the first time but contains a Core library with the same version that was previously installed directly.
Introduce an installation log to display a version history (with install date) in Permissions > Settings > Install.
=> Fix inconsistencies in update script triggering; introduce installation log

classes/PublishPress/Permissions/TermFiltersAdministrator.php
Permissions > Settings > Core > Front End > "Performance: Don't filter category / tag counts" was not applied for Administrator
=> Plugin settings: Tag count filtering disable not applied for Administrator

classes/PressShack/LibWP.php
The failed detection could cause various functional errors, including incorrect category / term assignment filtering.
=> Gutenberg usage triggered by another plugin was improperly detected

modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
On some sites, this caused Subcategory posts to be improperly hidden on Category pages.
=> Remove redundant add_filter() calls in PublishPress\Permissions\CollabHooks

classes/PublishPress/Permissions/DB/Groups.php
Follow up on previous correction to this function's output type, correcting the setting of $cols variable and adjusting conditional logic, which was adapted in the non-set variable.
=> PHP Warning on PublishPress\Permissions\Groups::getGroupsForUser() call

classes/PublishPress/Permissions.php, classes/PublishPress/Permissions/UI/SettingsAdmin.php, classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php, classes/PublishPress/PermissionsHooks.php
Option to restore previous behavior by suppressing front end term filtering under some conditions
=> Legacy plugin behavior: Settings > Advanced > Limit front-end term filtering

classes/PublishPress/Permissions/TermFilters.php
Prevent empty categories from being excluded from category selection under some conditions.
Support constant PRESSPERMIT_LEGACY_TERM_FILTERS_ARGS to revert to previous behavior.
Support constant PRESSPERMIT_REST_TERM_FILTER_SHOW_EMPTY for additional assurance that empty categories will not be excluded from selection UI.
=> Resolve category filtering error in Gutenberg on some installations

classes/PublishPress/Permissions.php, classes/PublishPress/PermissionsHooks.php
=> ACF: Type-specific capabilities not enforced for CPT unless explicitly configured in ACF settings

modules/presspermit-collaboration/classes/Permissions/Collab/CapabilityFiltersAdmin.php
Do not allow media deletion under these conditions unless "Users can always edit their own attachments" setting is enabled.
Fixes #1160
=> Media should not be editable or deletable if attached to an uneditable post

classes/PublishPress/Permissions/CapabilityFilters.php
Custom Post Type UI: Specific Permissions for editing do not grant access under some configurations.
To enable this fix, define constant PRESSPERMIT_EXTRA_POST_CACHE_DELETE
=> Experimental fix for Custom Post Type UI

modules/presspermit-collaboration/presspermit-collaboration.php, modules/presspermit-import/presspermit-import.php
These were redundant / ineffective translation calls, as the module title is set with translation in another function after the init action.
=> On translated WP 6.7 sites, pre-init translations cause an error

classes/PublishPress/Permissions/PostFilters.php, classes/PublishPress/PermissionsHooks.php
Since this issue has only been encountered by one user and may be strongly related to third party custom code, don't risk side effects on other sites by applying the safeguard too broadly.
=> Apply safeguard on query filter; enable via constant

classes/PressShack/LibWP.php
If another plugin hooks into the use_block_editor_for_post filter and does not validate the post argument, a fatal error could occur.
=> Fatal error adding page if another plugin hooks into use_block_editor_for_post

classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php, classes/PublishPress/Permissions/UI/SettingsTabCore.php
Under some site configurations, this section previously displayed contextual guidance regarding filtering of the Posts / Pages listing. This output has been moved to the Content Filtering section of the Advanced tab.
Fixes #1294
=> Plugin Settings section "Admin Back End" is empty with free plugin

classes/PublishPress/Permissions/UI/SettingsAdmin.php
=> Permissions Settings: PHP warning for undefined array index under some conditions

modules/presspermit-collaboration/classes/Permissions/Collab/PostTermsSave.php
The pre_tax_input filter passes a 2D array with taxonomy as the first key. However, other code may incorrectly filter it upstream.
Fixes #1347
=> Fatal error if other code filters pre_tax_input incorrectly

classes/PublishPress/Permissions/UI/AgentsChecklist.php
One of the class names had an errant brace character
=> User / Groups selection: invalid classname in div

classes/PublishPress/PermissionsHooks.php
Regular expressions were previously applied to ensure filtered post clauses have matching table prefixes for the currently switched site. These caught most of the problematic queries, but missed those which did not have explicitly qualified column names in the SELECT clause.
Fixes #1297
=> Multisite: Posts query error on installs with abnormal site switching (follow-up)

classes/PublishPress/Permissions/Capabilities.php, classes/PublishPress/Permissions/UI/SettingsTabCore.php
... but still apply previously stored setting (still adjustable by PP Capabilities)
=> Remove define_create_posts as a Permissions setting

common/css/edit-permissions.css
=> Permissions item count: improve background color contrast

classes/PublishPress/Permissions/UI/SettingsTabCore.php
Put strings directly in translation function argument so they are properly added to the .pot file.
=> Revert a string translation change

modules/presspermit-collaboration/classes/Permissions/Collab/PostTermsSave.php
Fixes #1624
If terms were filtered to null upstream, set to empty array.
=> PHP Warning on post update under some conditions

activation.php, classes/PublishPress/Permissions/CapabilityCaster.php, classes/PublishPress/PermissionsHooksAdmin.php
Make custom roles eligible for type-specific Extra Role assignment if their post capabilities for reading, editing or deletion differ from other pattern roles.
#1655
=> Default Role Usage configuration for qualifying Roles

classes/PublishPress/Permissions/UI/SettingsTabAdvanced.php, modules/presspermit-collaboration/classes/Permissions/CollabHooks.php
Enable Role Usage settings regardless of "Display all advanced settings" mode.
Make Role Usage link visible on Advanced tab regardless of "Display all advanced settings" mode.
#1655
=> Enable Role Usage

classes/PublishPress/Permissions/UI/Groups.php
* Screen title "Permissions" instead of "Permission Groups"
* Tab caption "User Groups" for matching plural form next to "Users"
=> Adjust Permissions screen title and tab caption

classes/PublishPress/Permissions/UI/AgentPermissions.php
We should remove this unwanted screen output, not just the redirect variable that triggers it.
=> Remove unused group created message and link

classes/PublishPress/Permissions/UI/AgentPermissionsAjax.php
Fixed https://github.com/publishpress/PublishPress-Permissions/issues/1731
=> fix an error of type E_ERROR crash report in AgentPermissionsAjax.php
